# source https://github.com/salines/vagrant-cakephp
# Mount WEB-APP dir
#$projectFolderPath = '~/projects/payboutique'
$projectFolderPath = '../code'

# Mount MYSQL-DATADir
$dbFolderPath = '../DBstore'

# Mount temp share
$shareFolderPath = '../Temp'

# Mount share logs
#$shareLogPath = '../Logs'

#SETUP VARS
PHP_V="7.4"


Vagrant.configure("2") do |config|
	config.vm.synced_folder $projectFolderPath, "/var/www/cake", create: true, :mount_options => ["dmode=777", "fmode=777"]
	#config.vm.synced_folder $dbFolderPath, "/var/lib/mysql", create: true, :mount_options => ["dmode=777", "fmode=777"]
	config.vm.synced_folder $shareFolderPath, "/tmp/share", create: true, :mount_options => ["dmode=777", "fmode=777"]
	#config.vm.synced_folder $shareLogPath, "/var/log/payboutique", create: true, :mount_options => ["dmode=777", "fmode=777"]

	config.vm.box = "debian/contrib-stretch64"
	config.vm.provider "virtualbox" do |v|
    	    v.memory = 1024*1
    	    v.cpus = 1
			v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
			v.name = 'ScienceD9'
	end

	config.vbguest.auto_update = false
	config.vbguest.no_remote = true
	config.vm.box_check_update = false
	config.vm.network "private_network", ip: "192.168.20.30"
	config.vm.hostname = "science"

	config.vm.provision "file", source: "source-file", destination: "/tmp/source-file"
	config.vm.provision "provision", type: :shell, path: "scripts/configure.sh", :args => [PHP_V]
	config.vm.provision :shell, path: "scripts/bootstrap.sh", run: 'always', :args => [PHP_V]
end
